apiVersion: v1
kind: Service
metadata:
  name: sso-frontend-sk-chen
  labels:
    name: assignment
spec:
  type: ClusterIP
  selector:
    component: sso
    student: sk-chen
  ports:
    - port: 3000
      targetPort: 3000
